name: kleverbird
description: kleverbird app to test shorebird release and patch
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.3
  get_it: ^9.2.0
  go_router: ^17.0.1
  provider: ^6.0.5
  restart_app: ^1.3.2
  shorebird_code_push: ^2.0.5
  terminate_restart: ^1.0.11

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - shorebird.yaml